version: '3.1'

services:

  db:
    image: postgres
    container_name: db
    restart: 'always'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data


  goscraper:
    image: goscraper
    container_name: goscraper
    restart: 'no'
    volumes:
      - ./scraper/congress:/congress
        #  node:
        #    container_name: congress_api
        #    build: 
        #      context: ./node
        #    restart: 'always'
        #    ports:
        #      - 3001:3001
        #    depends_on:
        #      - db
        #
        #  nginx:
        #    image: jonasal/nginx-certbot:latest
        #    restart: unless-stopped
        #    env_file:
        #      - ./nginx/nginx-certbot.env
        #    ports:
        #      - 80:80
        #      - 443:443
        #    volumes:
        #      - nginx_secrets:/etc/letsencrypt
        #      - ./nginx/user_conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
