apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: postgres-operator
  labels:
    type: local
spec:
  storageClassName: base
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sanjee/IdeaProjects/congress_api/scraper/congress"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: postgres-operator
spec:
  storageClassName: base
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi