apiVersion: apps/v1
kind: Deployment
metadata:
  name: csearch-api
  namespace: postgres-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csearch-api
  template:
    metadata:
      labels:
        app: csearch-api
    spec:
      containers:
        - name: csearch-api
          image: csearch.api:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_URI
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: uri } }
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                memory: "256Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: csearch-api
  namespace: postgres-operator
spec:
  selector:
    app: csearch-api
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer