apiVersion: apps/v1
kind: Deployment
metadata:
  name: csearch-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csearch-api
  template:
    metadata:
      labels:
        app: csearch-api
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      containers:
        - name: csearch-api
          image: s4njee/csearch-node
          ports:
            - containerPort: 3001
          env:
            - name: DB_URI
              value: "postgresql://postgres:postgres@postgres:5432/csearch"
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: congress-service
spec:
  selector:
    app: csearch-api
  ports:
    - port: 3001 

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: node-ingress
#  namespace: postgres-operator
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: "letsencrypt-staging"
#spec:
#  tls:
#  - hosts:
#    - api2.s4njee.com
#    secretName: csearch-tls
#  rules:
#  - host: "api2.s4njee.com"
#    http:
#      paths:
#      - pathType: Prefix
#        path: "/"
#        backend:
#          service:
#            name: congress-service
#            port:
#              number: 3001
#
