kind: PersistentVolume
apiVersion: v1
metadata:
  name: csearch-pv-volume
  labels:
    type: local
    app: csearch
spec:
  storageClassName: default
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/csearch/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: congress-pv
  labels:
    app: csearch
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi